sensor_kit_base_link:
  camera0/camera_link:
    pitch: 0.0
    roll: 0.0
    x: 0.12594
    y: 0.09297
    yaw: 0.3491
    z: -0.13525
  camera1/camera_link:
    pitch: 0.0
    roll: 0.0
    x: 0.12594
    y: -0.09297
    yaw: -0.3491
    z: -0.13525
  camera2/camera_link:
    pitch: 0.0
    roll: 0.0
    x: 0.0
    y: -0.2286
    yaw: -1.5708
    z: -0.0635
  camera3/camera_link:
    pitch: 0.0
    roll: 0.0
    x: -0.07
    y: -0.6985
    yaw: -1.5708
    z: -0.254
  camera4/camera_link:
    pitch: 0.0
    roll: 0.0
    x: -0.12594
    y: -0.09297
    yaw: 3.4907
    z: -0.13525
  camera5/camera_link:
    pitch: 0.0
    roll: 0.0
    x: -0.12594
    y: 0.09297
    yaw: 2.7925
    z: -0.13525
  camera6/camera_link:
    pitch: 0.0
    roll: 0.0
    x: 0.0
    y: 0.2286
    yaw: 1.5708
    z: -0.0635
  camera7/camera_link:
    pitch: 0.0
    roll: 0.0
    x: -0.07
    y: 0.6985
    yaw: 1.5708
    z: -0.254
  gnss_link:
    pitch: 0.0
    roll: 0.0
    x: -0.8426
    y: 0.0
    yaw: 0.0
    z: -1.192
  imu_link:
    pitch: 0.0
    roll: 0.0
    x: -0.8426
    y: 0.0
    yaw: 0.0
    z: -1.192
  lidar_left_base_link:
    pitch: 0.0
    roll: -1.2217
    x: 0.08
    y: 0.7493
    yaw: 0.0
    z: -0.2159
  lidar_right_base_link:
    pitch: 0.0
    roll: 1.2217
    x: 0.08
    y: -0.7493
    yaw: 0.0
    z: -0.2159
